# This is a basic workflow to help you get started with Actions

name: build README.md

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4.0.0
        with:
          python-version: 3.9
      
      - name: generate README.md
        run: |
          cd ${{ github.workspace }}
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          python3 build.py
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
