# This is a basic workflow to help you get started with Actions

name: build README.md

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4.0.0
        with:
          python-version: 3.9
      
      - name: generate README.md
        run: python3 build.py
